#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Nov 08, 2019 01:07:42 AM IST  platform: Linux

import sys
import MySQLdb

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk
from tkinter import messagebox
try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import delete_support

def click_home():
	global root
	root.destroy()
	root = None

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = DEL (root)
    delete_support.init(root, top)
    root.mainloop()

w = None
def create_DEL(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = DEL (w)
    delete_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_DEL():
    global w
    w.destroy()
    w = None

class DEL:
    def delete_farmer(self):
        aadhar = self.Entry1.get()
        if len(aadhar) == 12: 
            try:
                self.cursor_del.execute("DELETE FROM farmer WHERE aid = {}".format(aadhar))
                self.db_del.commit()
                messagebox.showinfo("Deletion Successful", aadhar + " Successfully deleted")
            except:
                messagebox.showerror("Deletion Error", aadhar + " is not present")
        else:
            messagebox.showerror("Deletion error", "12 digit Aadhaar Number required")

    def __init__(self, top=None):
        try:
            self.db_del = MySQLdb.connect("localhost","shivam","","FARMER")
            self.cursor_del = self.db_del.cursor()
        except:
    	    print('hi')
    	
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family gothic -size 15 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"

        top.geometry("725x573+391+117")
        top.minsize(1, 1)
        top.maxsize(1351, 738)
        top.resizable(1, 1)
        top.title("Delete Farmer Data")
        top.configure(background="#91d8d3")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.028, rely=0.07, relheight=0.41, relwidth=0.945)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")

        self.delete = tk.Button(self.Frame1)
        self.delete.place(relx=0.774, rely=0.426, height=35, width=130)
        self.delete.configure(activebackground="#6bd7ed")
        self.delete.configure(background="#6ed86a")
        self.delete.configure(font=font9)
        self.delete.configure(text='''Delete''')
        self.delete.configure(command=self.delete_farmer)

        self.aadhar = tk.Label(self.Frame1)
        self.aadhar.place(relx=0.029, rely=0.426, height=35, width=139)
        self.aadhar.configure(background="#82d89e")
        self.aadhar.configure(font=font9)
        self.aadhar.configure(text='''Aadhaar No''')

        self.Entry1 = tk.Entry(self.Frame1)
        self.Entry1.place(relx=0.321, rely=0.426,height=37, relwidth=0.345)
        self.Entry1.configure(background="white")
        self.Entry1.configure(font=font9)
        self.Entry1.configure(takefocus="0")

        self.home = tk.Button(self.Frame1)
        self.home.place(relx=0.774, rely=0.766, height=35, width=130)
        self.home.configure(activebackground="#6bd7ed")
        self.home.configure(background="#6ed86a")
        self.home.configure(font="-family {gothic} -size 15")
        self.home.configure(takefocus="0")
        self.home.configure(text='''Home''')
        self.home.configure(command=click_home)

if __name__ == '__main__':
    vp_start_gui()





