#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Oct 28, 2019 02:21:42 PM IST  platform: Linux

import os
import sys
from subprocess import call
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import queries_support

def click_home():
	global root
	root.destroy()
	root = None

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    queries_support.set_Tk_var()
    top = query (root)
    queries_support.init(root, top)
    root.mainloop()

w = None
def create_query(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    queries_support.set_Tk_var()
    top = query (w)
    queries_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_query():
    global w
    w.destroy()
    w = None

class query:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font9 = "-family gothic -size 15 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("725x573+391+117")
        top.minsize(1, 1)
        top.maxsize(1351, 738)
        top.resizable(1, 1)
        top.title("Query Page")
        top.configure(cursor="arrow")

        self.TCombobox1 = ttk.Combobox(top)
        self.TCombobox1.place(relx=0.069, rely=0.209, relheight=0.096
                , relwidth=0.892)
        self.TCombobox1.configure(font=font9)
        self.TCombobox1.configure(state='readonly')
        self.TCombobox1.configure(textvariable=queries_support.combobox)
        self.TCombobox1.configure(takefocus="")

        self.title = tk.Label(top)
        self.title.place(relx=0.317, rely=0.105, height=45, width=259)
        self.title.configure(background="#8ad8d5")
        self.title.configure(font=font9)
        self.title.configure(text='''General Queries''')

        self.Listbox1 = tk.Listbox(top)
        self.Listbox1.place(relx=0.069, rely=0.401, relheight=0.51
                , relwidth=0.888)
        self.Listbox1.configure(background="white")
        self.Listbox1.configure(font="TkFixedFont")

        self.submit = tk.Button(top)
        self.submit.place(relx=0.828, rely=0.332, height=32, width=88)
        self.submit.configure(background="#a2d89c")
        self.submit.configure(font=font9)
        self.submit.configure(text='''Submit''')

        self.home = tk.Button(top)
        self.home.place(relx=0.828, rely=0.925, height=32, width=88)
        self.home.configure(activebackground="#f9f9f9")
        self.home.configure(background="#a2d89c")
        self.home.configure(font="-family {gothic} -size 15")
        self.home.configure(text='''Home''')
        self.home.configure(command=click_home)

if __name__ == '__main__':
    vp_start_gui()





